version: '3.8'

services:
  go-app:
    build: .
    container_name: pismo-assessment
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: mydatabase
    networks:
      - app-network

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:       # Add this healthcheck section
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
      interval: 5s

  go-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
    command: >
      sh -c "
        go test -v -covermode=atomic -coverprofile=coverage.out ./... &&
        go tool cover -func=coverage.out
      "

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
