[app]
  [app.server]
    host = "0.0.0.0"
    port = 8080
  [app.db]
    username = "user"
    password = "userpassword"
    host     = "mysql"
    dbname   = "mydatabase"
    port     = 3306
    charset = "utf8mb4"